name: Manual Update README

on:
  workflow_dispatch:

jobs:
  manual-update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "5534031+github-actions[bot]@users.noreply.github.com"

      - name: Run update-readme script
        working-directory: .repo/apps/toolbelt
        run: |
          uv sync
          uv run update_readme.py

      - name: Check for changes
        id: check-changes
        run: |
          # Check if there are any changes in the working directory
          if git diff --quiet && git diff --cached --quiet; then
            echo "changes_detected=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          else
            echo "changes_detected=true" >> $GITHUB_OUTPUT
            echo "Changes detected"
            echo "Changed files:"
            git diff --name-only
            git diff --cached --name-only
          fi

      - name: Show README.md (if changes detected)
        if: steps.check-changes.outputs.changes_detected == 'true'
        run: cat README.md

      - name: Create Pull Request (if changes detected)
        if: steps.check-changes.outputs.changes_detected == 'true'
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          title: "ci(readme) Manual update - sort tools and update README.md"
          branch: ci/manual-update-readme/${{ github.run_id }}
          base: main
          commit-message: "ci: manual update - sort tools, dedupe, and update README.md"
          add-paths: |
            README.md
            .repo/tools.json
          body: |
            This PR contains manual updates to the repository via the manual update workflow.
            
            - Sorted tools.json file alphabetically
            - Deduplicated any duplicate tool entries
            - Updated tools table in README.md
            
            Manually triggered by: @${{ github.actor }}
            Run ID: ${{ github.run_id }}

      - name: Auto-merge Pull Request (if PR created)
        if: steps.check-changes.outputs.changes_detected == 'true' && steps.create-pr.outputs.pull-request-number != ''
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          pr_number="${{ steps.create-pr.outputs.pull-request-number }}"
          echo "Auto-merging PR #$pr_number"
          
          # Wait a moment for the PR to be fully created
          sleep 5
          
          # Check if PR exists and is mergeable
          pr_status=$(gh pr view $pr_number --json mergeable,state --jq '.state')
          echo "PR state: $pr_status"
          
          if [ "$pr_status" = "OPEN" ]; then
            echo "Attempting to merge PR #$pr_number"
            gh pr merge $pr_number --squash --delete-branch --subject "ci: manual update - sort tools, dedupe, and update README.md"
            echo "PR #$pr_number merged successfully"
          else
            echo "PR #$pr_number is not in a mergeable state: $pr_status"
            exit 1
          fi

      - name: Summary
        run: |
          if [ "${{ steps.check-changes.outputs.changes_detected }}" = "true" ]; then
            echo "✅ Changes detected and processed"
            if [ "${{ steps.create-pr.outputs.pull-request-number }}" != "" ]; then
              echo "✅ PR #${{ steps.create-pr.outputs.pull-request-number }} created and auto-merged"
            fi
          else
            echo "ℹ️ No changes detected - repository is already up to date"
          fi
