name: Run on PR merge if tools.json changed

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  run-on-pr-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            .repo/tools.json

      - name: Debug changed files
        run: |
          echo "Any changed files: ${{ steps.changed-files.outputs.any_changed }}"
          echo "All changed files: ${{ steps.changed-files.outputs.all_changed_files }}"

      - name: Install uv
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Configure Git
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "5534031+github-actions[bot]@users.noreply.github.com"

      - name: Run update-readme pipeline if tools.json changed
        if: steps.changed-files.outputs.any_changed == 'true'
        working-directory: .repo/apps/toolbelt
        run: |
          uv sync
          uv run update_readme.py

      - name: Show README.md
        if: steps.changed-files.outputs.any_changed == 'true'
        run: cat README.md

      - name: Create Pull Request
        if: steps.changed-files.outputs.any_changed == 'true'
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          title: "ci(readme) Update README.md tools table"
          branch: ci/update-readme/${{ github.run_id }}
          base: main
          commit-message: "ci: update README.md and sorted tools.json"
          add-paths: |
            README.md
            .repo/tools.json
          body: |
            This PR updates README.md autogenerated content via the CI pipeline.
            
            - Sorted tools.json file
            - Updated tools table in README.md
            
            Triggered by PR #${{ github.event.pull_request.number }}

      - name: Auto-merge Pull Request
        if: steps.changed-files.outputs.any_changed == 'true' && steps.create-pr.outputs.pull-request-number != ''
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          pr_number="${{ steps.create-pr.outputs.pull-request-number }}"
          echo "Auto-merging PR #$pr_number"
          
          # Wait a moment for the PR to be fully created
          sleep 5
          
          # Check if PR exists and is mergeable
          pr_status=$(gh pr view $pr_number --json mergeable,state --jq '.state')
          echo "PR state: $pr_status"
          
          if [ "$pr_status" = "OPEN" ]; then
            echo "Attempting to merge PR #$pr_number"
            gh pr merge $pr_number --squash --delete-branch --subject "ci: update README.md and sorted tools.json"
            echo "PR #$pr_number merged successfully"
          else
            echo "PR #$pr_number is not in a mergeable state: $pr_status"
            exit 1
          fi
